//
//  StickerSharing.swift
//  LezgiKeyboard
//
//  Exports the eagle sticker pack to WhatsApp (third-party sticker pack
//  pasteboard API) and Telegram (TelegramStickersImport library).
//  Assets live in MessengerStickers/ and are generated by
//  scripts/gen_messenger_stickers.py, which also owns the emoji mapping.
//

import UIKit
import TelegramStickersImport

enum StickerSharingError: LocalizedError {
    case appNotInstalled(String)
    case exportFailed

    var errorDescription: String? {
        switch self {
        case .appNotInstalled(let app):
            return String(localized: "\(app) is not installed on this device")
        case .exportFailed:
            return String(localized: "Could not prepare the sticker pack. Please try again.")
        }
    }
}

enum StickerSharing {

    // must stay in sync with scripts/gen_messenger_stickers.py
    private static let stickers: [(file: String, emojis: [String])] = [
        ("salam",      ["👋"]),
        ("thanks",     ["🙏"]),
        ("sweetheart", ["🥰"]),
        ("great",      ["👍"]),
        ("yes",        ["✅"]),
        ("no",         ["❌"]),
        ("howareyou",  ["🤗"]),
        ("loveyou",    ["❤️"]),
        ("sorry",      ["🥺"]),
        ("bravo",      ["👏"]),
        ("congrats",   ["🎉"]),
        ("welcome",    ["🤝"]),
        ("comehere",   ["🏃"]),
        ("morning",    ["☀️"]),
        ("angry",      ["😠"]),
        ("goodnight",  ["😴"]),
        ("prayer",     ["🤲"]),
        ("lezginka",   ["🕺"]),
        ("khinkal",    ["🥟"]),
        ("lezgiflag",  ["🦅"]),
    ]

    private static func assetData(_ name: String, _ ext: String) throws -> Data {
        guard let url = Bundle.main.url(forResource: name, withExtension: ext),
              let data = try? Data(contentsOf: url) else {
            throw StickerSharingError.exportFailed
        }
        return data
    }

    // MARK: - WhatsApp

    static func addToWhatsApp() throws {
        guard let scheme = URL(string: "whatsapp://stickerPack"),
              UIApplication.shared.canOpenURL(scheme) else {
            throw StickerSharingError.appNotInstalled("WhatsApp")
        }

        let pack: [String: Any] = [
            "identifier": "com.lekitech.lezgikeyboard.eagle",
            "name": "Lezgi Stickers",
            "publisher": "LekiTech",
            "tray_image": try assetData("tray", "png").base64EncodedString(),
            "ios_app_store_link": "",
            "android_play_store_link": "",
            "stickers": try stickers.map { sticker in
                [
                    "image_data": try assetData(sticker.file, "webp").base64EncodedString(),
                    "emojis": sticker.emojis,
                ] as [String: Any]
            },
        ]

        guard let json = try? JSONSerialization.data(withJSONObject: pack) else {
            throw StickerSharingError.exportFailed
        }
        UIPasteboard.general.setItems(
            [["net.whatsapp.third-party.sticker-pack": json]],
            options: [
                .localOnly: true,
                .expirationDate: Date().addingTimeInterval(60),
            ])
        UIApplication.shared.open(scheme)
    }

    // MARK: - Telegram

    static func addToTelegram() throws {
        let set = StickerSet(software: "LezgiKeyboard", type: .image)
        for sticker in stickers {
            try set.addSticker(data: .image(assetData(sticker.file, "webp")),
                               emojis: sticker.emojis)
        }
        do {
            try set.import()
        } catch StickersError.telegramNotInstalled {
            throw StickerSharingError.appNotInstalled("Telegram")
        }
    }
}
